GObject: Implement get/set of non-introspected properties
romgrk/node-gtk pull request #209
Opened 2020-08-23 19:51 UTC by peat-psuwit

This commit implements a NamedPropertyHandler which enable get/set of
non-introspected properties. This is done by re-factoring ObjectProperty
{Getter,Setter} to seperate actual property handling to helper functions
under gobject.cc, then implement the handler using those functions.

The handler uses kNonMasking flag, which make V8 skips the handler if
the object already has the property. This flag is available in Node.js >=
v4.x [1], but I believe we don't have to care about Node.js that old.

Fixes #83. Also fixes partially #183.

[1] https://github.com/nodejs/nan/issues/667#issuecomment-298598348

2020-08-24 18:12 UTC, romgrk commented
Thanks! Will review this week

2020-09-08 16:27 UTC, peat-psuwit commented
Ping the developer.

2020-09-09 17:50 UTC, romgrk requested changes
Nice work! I've left a few comments for minor things but it LGTM. One question though, what do you think of https://github.com/romgrk/node-gtk/pull/206? I feel like this PR trades complexity inside node-gtk for ease-of-use for the users of node-gtk, which I'm most of the time in favour, but I'd be happy to have your feeling on that.

2020-09-09 17:50 UTC, romgrk commented on src/gobject.cc
> +        WARN("ObjectPropertySetter: null GObject; cant get %s", prop_name);
"can't **set**"

2020-09-09 17:50 UTC, romgrk commented on src/gobject.cc
> +    GObject *gobject = GNodeJS::GObjectFromWrapper (self);
`GObjectFromWrapper` can be called without the prefix.

2020-09-09 17:50 UTC, romgrk commented on src/gobject.cc
> +                                            const v8::PropertyCallbackInfo<Value>& info) {
It's "fallback", not "failback" (repeated a few times).

2020-09-13 16:32 UTC, peat-psuwit commented
Ok, all your comments should be fixed.

Regarding this PR vs #206, I would say that I prefer behavior that's similar to `gjs`. That is, any property should be able to get/set using JS object syntax (as this PR does). I also want to have a functional `{get,set}Property()` function based on what `gjs` provides. The problem is, even `gjs` doesn't actually have functional `get_property()`. So, I'm not sure what we should do with this function.

```
gjs> const GObject = imports.gi.GObject
gjs> const Gst = imports.gi.Gst
gjs> Gst.init(null)

gjs> const e = Gst.ElementFactory.make('videotestsrc', null)
gjs> e.timestampOffset
0
gjs> const v = new GObject.Value()
gjs> v
[boxed instance proxy GIName:GObject.Value jsobj@0x7f8381d85380 native@0x55e8c4d91040]
gjs> v.init(GObject.TYPE_INT64)
0
gjs> e.get_property('timestamp-offset', v)
Segmentation fault (core dumped)
```

2020-09-13 21:51 UTC, romgrk commented
LGTM. And yes, a `(g|s)etProperty` would be nice, and doesn't seem too hard to add looking at what we already have in this PR. Do you want to add it before I merge?

2020-09-13 21:51 UTC, romgrk approved these changes

2020-09-14 09:38 UTC, peat-psuwit commented
`{get,set}Property` can be in another PR. However, my point is that I'm not sure what interface these functions should provide, given that `gjs`'s behavior is broken.

IMO, the behavior of #206 (directly returning/receiving property value as JS value) is probably OK, but we might want to re-name it to simply `get()` and `set()` (think `g_object_{get,set}()`), so that we can implement proper GValue-based `{get,set}Property` later if/when their behavior on `gjs` is clear.

2020-10-02 19:07 UTC, merged

2020-10-02 19:07 UTC, romgrk commented
I think `get`/`set` is too comon to be used in the base Object prototype, I'd rather use a longer name. Also I don't consider `gjs` the reference. If we can match their API fine, but this is different.

Anyway I'll merge this and do some testing on #206. Thanks for the PR!